### ISSUE TITLE
Extend parsing system

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#10]
- [x] ignore articles
- [x] objects have a list of names and list of adjectives (and adverbs?), parser checks these to find a match, if more than one match parser asks "did you mean" and lists short descriptions of both
- [x] Consider making a special category for intransitive verbs (verbs that don't need a direct object, like "sneeze", "inventory", "south", etc). Otherwise need to guard every single verb with "if not oDO then: return"
- [x] Consider making a class for "Verb" which has the string (and synonyms?), the function, and flags for things like whether verb can be transitive
- [x] Consider matching prepositions to determine sentence structure (transitive/intransitive verb, presence of a direct and an indirect object)

Basic idea is a parser that matches up words with objects that represent parts of speech, consuming those words as it goes, to conform to one of a couple possible sentence structures.

**Comment by 1Bayshore** [comment]
You should check off the things that are done here, because some of them are. Some of these are already handled. This should probably also be closed.

**Comment by davedotluebke** [comment]
Everything is implemented, closing.
