### ISSUE TITLE
Gameclient occasionally stops responding

### ISSUE THREAD

**Issue by rivques** [davedotluebke/old-skool-text-game#108]
Occasionally, the client will stop responding to input. The server is still running, but I can't do anything from the client and I lose all my saved data. I can type as much as I want, but I don't get a response.

**Comment by 1Bayshore** [comment]
I've had a similar issue when the computer goes to sleep. Do you think that's causing it?

**Comment by rivques** [comment]
I don't know. I would be playing as normal and suddenly I would stop getting responses. It seemed to only happen with one player though.

**Comment by rivques** [comment]
Closing, as has not been reproduced.
