### ISSUE TITLE
Improve sign-on experience for brand new players

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#112]
We need slightly more direction for brand-new players to explain how to play the game. 

Consider an interactive tutorial, e.g., "Try typing, 'go north'".

**Comment by 1Bayshore** [comment]
Here's a checklist of the improvements we intend to make:
- [ ] Improve landing pad page
  - [ ] Put instructions on this page (e.g. help text)
- [ ] Improve character creation process
 - [ ] Make it clear how to complete the process
 **We should have something explaining that you have to type `enter mirror` to continue**
 - [ ] Currently, players can accidentally skip the adjectives. Make sure all players know how to select adjectives and do so.
 - [ ] Maybe you could get two random adjectives by default and then be able to switch them?
- [ ] Make sure that players read the signs. (Maybe turn this into a full-blown guided tutorial.)

**Comment by 1Bayshore** [comment]
A basic guided tutorial is implemented, making suggestions after a while. We could still add many more messages to make it more clear.

**Comment by 1Bayshore** [comment]
The interactive tutorial also comes up for players who aren't brand new. We need to work more on this.
