### ISSUE TITLE
Are game restarts always working?

### ISSUE THREAD

**Issue by 1Bayshore** [davedotluebke/old-skool-text-game#117]
As far as I can tell, the game restarting code isn't always working properly. Some testing suggests that it's something specific, because if I just log in and make it restart, it works fine. Is there something somewhere in the game causing this? (The usual suspects: `scroll`, combat, `save_player`.)

**Comment by davedotluebke** [comment]
Game restarts seem much more robust. Closing this for now; if we find a reproducible problem we can open a new issue.
