### ISSUE TITLE
Simplify NPC "scripts" and "quotes" processing

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#12]
I realized that quotes could just be implemented as one-line scripts. We should just take quotes out of the system. 

Also, python has the nice str.splitlines() function which breaks a multi-line string up into individual lines. I think we should use this so that we can specify all quotes/scripts as a single string, potentially with multiple lines that will be read one at a time. See 

https://docs.python.org/3/library/stdtypes.html#string-methods

**Comment by 1Bayshore** [comment]
Fixed this issue.
