### ISSUE TITLE
Finishing the library

### ISSUE THREAD

**Issue by 1Bayshore** [davedotluebke/old-skool-text-game#121]
The school's library is still incomplete. We should add some of the features we have considered before, like bookshelves full of books where you scan for titles.

**Comment by 1Bayshore** [comment]
While we are in the process of updating the bookshelf, we should make the secret book a bit less secret. Perhaps when you look at the bookshelf you notice a `worn book` and if you `take worn book` then you open the secret passage.

**Comment by davedotluebke** [comment]
@1Bayshore seems like this can be closed now?
