### ISSUE TITLE
Nobody can upload except `scott` due to `game.player_edit_privelages`

### ISSUE THREAD

**Issue by rivques** [davedotluebke/old-skool-text-game#134]
In the `__init__` function of `Game`, `game.player_edit_privelages` and `game.player_read_privelages` are hardcoded to include only the user `scott`. This should be changed so that all wizards can edit and read. Maybe on player login/logout, the dictionaries are updated? Should there even be read permissions, since all the code is available on GitHub? Or should wizards be able to read all but the save files, in order to prevent them from seeing and changing who has wprivelages, usernames and items, etc.

**Comment by davedotluebke** [comment]
This is fixed as part of fe5b37db842c64e74ca77f4dab4cf90640bcf57b!
