### ISSUE TITLE
wizards should be able to edit their own files and read most files 

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#139]
Currently this is hardcoded in gameserver.py on a wizard-by-wizard basis. 

- Administrators should be able to read and write any file in the game. 
  - alternative: admins can read any file but some files they can't write from game (i.e. they have to log into the server and edit files directly)
- Wizards should be able to edit anything in their home directory

**Comment by davedotluebke** [comment]
Here is the planned usage message:

Usage: `debug [sec] [level] obj`

The *obj* argument may be:
- a visible object or creature
- an object id (i.e. an entry in `Thing.ID_dict[]`)
- a path of the form 'domains.school.example_object'
- the keyword *here*, which specifies the room containing the player
- the keyword *me*, which specifies the player object itself.

The optional *\[sec\]* argument specifies the duration, in seconds, of the debug logging. The default is 60 seconds.

The optional *\[level\]* argument must be one of `debug`, `info`, `warning`, or `error`. All log messages at the specified level are displayed. If left unspecified, *\[level\]* defaults to `debug`.

**Comment by 1Bayshore** [comment]
When fixed, this will close #134.

**Comment by davedotluebke** [comment]
This is closed by 9d85f5343ea43b9acd33cc39edd2be1e34fa69c5
