### ISSUE TITLE
Consider a simpler way of handling darkness & light emitters

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#16]
Right now the way light is handled is pretty complicated: every room has a default light level, which if zero means the room is dark by default. Light emitters (like the flashlight object) can increase this light level. This is implemented by having the light emitters add to the light level when they enter the room, and reduce the light level again when they leave the room. They also need to adjust the light level when they are activated (e.g. "turn on flashlight"). There are some weird corner cases, such as if the flashlight is placed in a bag which is then closed and carried into a room. When the container is opened there is no code which knows to check if the flashlight is on, and if so increment the room light. 

In retrospect I propose a simpler system: The look_at() action for the room should check if the room is dark by default. If so, it checks the contents of the room and recursively checks the contents of any containers (including players/creatures) in the room that have the see_inside flag set. It totals the light level produced by any light emitters it finds, and if the overall light level is positive, it prints the room description - otherwise it says "it's too dark to see". Similarly the emit() or perceive() functions can check the default light level of the room, and if that level is zero, check recursively for light sources before printing anything visual. 

Probably should avoid the temptation to over-engineer the handling of darkness. Realistically, it will be very rare for players to be in dark rooms without a light source.

**Comment by 1Bayshore** [comment]
This was implemented.
