### ISSUE TITLE
Implement liquids

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#20]
Liquids are a special subclass of Scenery object. We inherit from Scenery because the player generally can't interact directly with liquids; they are usually in a container. We add a couple special actions: pour, drink, and fill. 

The "pour" verb is complex and should work like this: 

- "pour potion out" OR "pour potion out"
  - `oDO == self, oIDO == None, sPrep == "out"`
  - respond "You pour the potion out and the resulting puddle quickly disappears."; delete potion object
- "pour potion"
  - `oDO == self, oIDO == None, sPrep == None`
  - Respond "What do you want to pour the potion into?"
- "pour potion into cauldron" 
  - `oDO == self, oIDO == <liquid container>, sPrep in ("in", "into")`
  - respond "you pour the potion into the <container>"; extract potion object & insert in container

We should also make a special flag for Container to indicate if it can hold liquids. The initial idea was to make a special LiquidContainer class, but in retrospect that's not necessary; the Liquid object will support the special verbs (pour, drink, fill) directly.

**Comment by 1Bayshore** [comment]
This was implemented.
