### ISSUE TITLE
Use "bare hands" when no weapon to wield

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#24]
When attacking, an NPC checks if it is wielding a weapon and if not, wields the first weapon it finds in its inventory. If it doesn't find a weapon that is currently an error. Instead, have the creature attack using it's "bare hands". 

Couple subissues: 
- add default weapon(s) to the things you can set when creating a monster; if more than one is provided they will be picked at random from a list. This is just "scenery" and doesn't change the amount of damage, chances of hitting, etc. E.g. ```dragon.set_weapons('terrible claws', 'fearsome sharp teeth', 'wicked spiked tail')```
- Is the cleanest way to do to make "bare hands" a weapon? Not clear.

**Comment by 1Bayshore** [comment]
This was implemented.
