### ISSUE TITLE
Clean up half-done code

### ISSUE THREAD

**Issue by 1Bayshore** [davedotluebke/old-skool-text-game#25]
A lot of little snippets of code for various little projects that we never finished are still hanging around in the code. We should either finish those projects or delete that code.

**Comment by davedotluebke** [comment]
Like what? Maybe you should tag snippets like this when you find them with
CLEANUP or something.

**Comment by davedotluebke** [comment]
The game is quite mature now and this issue is over three years old. Closing for now and we should open new issues specific to any particular dead/unfinished code we find.
