### ISSUE TITLE
Execute code from console

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#26]
A simple version of this is now implemented; see commit 3917bbf. You can type `execute print(self.location)` at the console prompt and it will do the right thing, printing the ID of the room containing the player. Exceptions are caught and reported without effect, so that a mistyped command doesn't crash the game. I also created a default alias 'x' to reduce typing, e.g. `x print(self)`.

One thing I'd like to do in the future is have the parser recognize strings (meaning text enclosed with " or ' marks) and preserve capitalization, whitespace, etc. inside strings. For now I just hard-coded some commands which should preserve exactly what the user typed: "execute", "say", and "shout". 

@1Bayshore check it out! And see how it was implemented by clicking on the commit number above, it was really very simple to add.

**Comment by 1Bayshore** [comment]
Opened #37 for second paragraph. Closing this.
