### ISSUE TITLE
Support registering future events

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#27]
Right now we have a heartbeat system, but no easy way to allow objects to say, "in 20 heartbeats do this". But this is going to be a very common use case for heartbeats. Torches will want to go out after a certain amount of time; invisibility potions should wear out; cauldrons should bubble and smoke before producing their product. Right now it would be a pain to implement something like a torch going out after 20 turns. The torch object would have to set a counter when it is lit, then register a heartbeat and decrement the counter every turn until it reaches zero, then call the code to burn out. This feels cumbersome and error-prone, and is not very efficient if you imagine hundreds or thousands of objects getting called to decrement their counters every heartbeat. 

Instead we should implement an **events** system, where objects can provide a function and a number of turns (or seconds) in the future when that function should be called. Then the game server can keep a sorted list of upcoming events (this is called a _priority queue_ in computer science), and each heartbeat can check the first event on the list (i.e. the one that should happen soonest) to see whether the invoke the event.

**Comment by 1Bayshore** [comment]
Implemented an events system. Is very useful.
