### ISSUE TITLE
when "take <obj>" verb fails, it silently disappears the object

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#3]
when "take <obj>" should fail (e.g. obj is too heavy) it still extracts obj from its container, then fails to insert into the new container (the player), but still prints "you take the <obj>" 

The result is the object disappears from where it was and is no longer attached to a container. 

Seems like the take verb_func should check to see if the object can be extracted and inserted before doing so. Might need to create new functions to separate testing if extract/insert are valid from the actual operations. 

Or another approach: combine extract and insert into a single function, which returns a value indicating if the operation was successful. This one seems simpler.

**Comment by 1Bayshore** [comment]
Seems like it works now.
