### ISSUE TITLE
Add combat system.

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#4]
Add combat system. Each creature has a list of current enemies they are fighting. After one or more heartbeat(s), fighters will attack with whatever weapon they wield. 

Add some new statistics for creatures and weapons/armor:
- [x] 1. Chance of hitting depends on **armor class (AC)** of defending creature, modified by **armor bonus**
- [x] 2. Chance of hitting depends on **combat skill** of attacking creature, modified by **weapon accuracy**
- [x] 3. Damage upon hit depends on **weapon damage**, modified by **strength** of attacker.
- [ ] 4. Frequency of attacks (# of heartbeats between attacks) depends on attacker **dexterity**, modified by weapon and armor **unwieldiness**

When a creature attacks a player, the player must explicitly type an _attack_ command ("attack orc", "swing sword at orc", ...) to start attacking them back (this is still under discussion). Once a creature or player is attacking another, they will continue to attack until the enemy is dead or until they type a _withdraw_ command to stop attacking. While they are in combat they cannot exit the room; to run away from a fight a player must first withdraw from combat, exposing themselves to a blow or two before they get the chance to exit the room. 

Other features to code: 
- [ ] A player must _wear_ an Armor item to have an effect.
- [ ] A player must _wield_ a weapon item to have an effect.

**Comment by 1Bayshore** [comment]
Currently, the monster can attack, and is overpowered(rebalancing necessary). Also, the player cannot attack yet.

**Comment by 1Bayshore** [comment]
Here is the actual code used to compute whether the attack hits and if so the damage done:
```
chance_of_hitting = self.combat_skill + self.weapon_wielding.accuracy - enemy.get_armor_class()
if random.randint(1, 100) <= chance_of_hitting:
    d = self.weapon_wielding.damage
    damage_done = random.randint(int(d/2), d) + self.strength / 10.0
```
where get_armor_class() is defined as:
```
def get_armor_class(self):
    return self.armor_class + (0 if not self.armor_worn else self.armor_worn.bonus)
```

**Comment by 1Bayshore** [comment]
Here is the actual code used to determine the attack frequency, or number of heartbeats between attacks:
```
    def attack_freq(self):
        try:
            return (20.0/self.dexterity + self.weapon_wielding.unwieldiness + self.armor_worn.unwieldiness)
        except AttributeError:
            return (20.0/self.dexterity)
```
and the code which uses this value, in `Creature.attack_enemy()` called every heartbeat:
```
        if self.attack_freq() <= self.attack_now:
            self.attack(attacking)
        else:
            self.attack_now += 1
```
