### ISSUE TITLE
Create a web client

### ISSUE THREAD

**Issue by 1Bayshore** [davedotluebke/old-skool-text-game#50]
# Create a web client
If a user wants to log on to the game, telnet shouldn't be the only way to make a connection in. For many players, a web client would be easier. We may want to make a custom `Node.js` client or find something which emulates telnet in a browser. We might also want to use panes in the user experience to separate input and output.

**Comment by dannyhuss** [comment]
In the meantime, the Ubuntu repositories have a program called [**kbtin**](https://github.com/kilobyte/kbtin) if you're running linux. It's a command line MUD program that separates the input from the output (among other things). What I did was put a file named **oad** in my home directory with the line:
`#session OAD localhost 9123`
to log in, open a terminal to your home directory and type:
`kbtin oad`
and to log out, type
`#end`
It's much nicer than using telnet directly with things like blue birds and butterflies flying around all willy-nilly.

**Comment by dannyhuss** [comment]
If anyone tries **kbtin**, you'll need to add `#charset UTF-8` to the beginning of the **oad** file or else unicode text will show up as a garbled mess.

**Comment by 1Bayshore** [comment]
This is working in the webclient branch, and we are ready to do a pull request and merge it back in. I'll open a couple issues for the remaining minor things.
