### ISSUE TITLE
Indentation not compatible with HTML 

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#58]
We have moved to HTML formatting of the output, which means that adding a '\t' to indent a line no longer has any effect. For example, this comes up when you "look" or enter a room: we would like to indent the objects and exits listed in that room to make them stand out.

Need to decide how to handle this. Could wrap any indented lines or lists in a `<blockquote>` tag. We currently replace the \t character with 4 &nbsp characters, but that doesn't work as we expected (just seems to show up as regular whitespace which HTML ignores).

**Comment by davedotluebke** [comment]
For that matter, we could use unnumbered lists (`<ul> <li> item 1 </li> </ul>`)

**Comment by davedotluebke** [comment]
Makes me wonder if what we REALLY ought to support is not HTML but Markdown.

**Comment by 1Bayshore** [comment]
Perhaps what we should do is use the css "text-indent" property, which indents text like you would expect a paragraph to be.
