### ISSUE TITLE
Extend DebugLog class

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#6]
Support: 
- [x] multiple levels of verbosity
- [x] auto-indentation
- [x] auto-labeling of the module/class/function that is logging the debug
- [x] provide keyword filtering so only debug messages (including the call stack) that match a given string are printed (I.e., "verbose Creature" would print out all debug messages called from methods of the Creature class, or that include 'creature' in the debug string.)

**Comment by 1Bayshore** [comment]
I have auto-labeling by the function name working, including the line number where `debug()` was called, but haven't figured out how to include the name of the class (to include the file would be possible though).

**Comment by 1Bayshore** [comment]
We allow all of these, so closing.
