### ISSUE TITLE
Consider reworking spawn system

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#69]
Currently the code for spawning is in Container.py. Seems awkward, perhaps we should find a different place. The spawn system isn't currently used; revisit this code at a later date.

**Comment by 1Bayshore** [comment]
What we really should do is implement the respawning with periodic "reload" commands that reset certain rooms in the game. However, since we don't use this code right now, we don't need to implement it now.

**Comment by rivques** [comment]
Closing. Refer to #120.
