### ISSUE TITLE
Simplify and streamline Action handling

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#70]
The current representation of Actions is clunky and over-engineered. It also wastes a lot of memory because every object created in the game replicates the Actions for every verb that applies to that object (see #29).

Two goals: 
 1. go back to a simpler dictionary-based mapping of which verbs enact which functions for every object in the game. 
 2. move the list of applicable Actions from the object (instance of a class) to the class, saving memory by having only one copy of most actions per class rather than one copy per action.
    - a challenge here will be Scenery objects, to which we add verbs after they are created. And occasionally an action might need to be added or modified for a specific object. For this reasons we will have an optional `obj_actions[]` list of verbs specific to the object. 

If a subclass specifically overloads a verb defined by the parent class, the code for the class should redefine the action associated with the verb. For example, the `Thing` class maps 'look' and 'examine' to `Thing.look_at()` which prints the long description of the thing, and the `Container` class needs to remap them to `Container.look_at()` in order to also list the contents of the container. So `Thing` will include something like:
```python
verb_dict = {"look":Thing.look_at(), "examine":Thing.look_at()}
```
and `Container` will include
```python
verb_dict = dict(Thing.verb_dict)  # make a copy so we don't change Thing's dictionary!
verb_dict["put"] = Container.put()           # a new verb, not found in Thing
verb_dict["look"] = Container.look_at()       # overloading a verb found in Thing
verb_dict["examine"] = Container.look_at()    # overloading a verb found in Thing
```
Note that these code blocks are part of the class definition itself, not part of a function (such as `__init__()`) called on a particular object of that class. Thus they don't refer to `self`.

**Comment by davedotluebke** [comment]
Realized three things:

1. The dictionary mapping verbs to actions should be called `actions` not `verb_dict`. 
2. Changing all the verbs and actions to the new system is going to be a lot of typing. There are over 100 Actions created in the game today, and almost half specify multiple verbs.
3.. Named tuples are a great way to represent Actions, much lighter weight than a class. The new definition of Action is simply: `Action = namedtuple('Action', ['func', 'trans', 'intrans']).`
4. To store a reference to a class method in a field attribute of the class itself, the reference must come after the method has been defined. This is what I struggled with in the comments to #29.  This means that all action functions should be defined near the top of the class, and the action list be created at the end: 
```python
class Armor(Thing):
    def __init__(self, default_name, path, bonus, unwieldiness, pref_id=None):
        ...
    def wear(self, p, cons, oDO, oIDO):
        ...
    def unwear(self, p, cons, oDO, oIDO):
        ...
    def armor_drop(self, p, cons, oDO, oIDO): 
        ...

    actions = dict(Thing.actions)  # make a copy, don't change Thing's dict!
    actions['wear'] =   Action(wear, True, False)
    actions['use'] =    Action(wear, True, False)
    actions['unwear'] = Action(unwear, True, False)
    actions['remove'] = Action(unwear, True, False)
    actions['drop'] =   Action(armor_drop, True, False)  # replace Thing "drop"
```

**Comment by 1Bayshore** [comment]
@davedotluebke we actually don't have to move the functions anywhere, as long as the definition is after them. Having them at the end of the class definition is actually helpful in most cases, prioritizing the essential functions that define a class.

We also might want to open another issue about reorganizing the order of functions inside a class. Currently, the order is mostly random. It would be easiest to fix while we're already going through all of the different classes in the game.
