### ISSUE TITLE
Parser: handle darkness correctly when choosing actions 

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#71]
The parser creates a list of relevant objects (objects which can provide a "verb action" the player can type, or objects that can serve as the direct or indirect object). This list includes the contents of the room and the (potentially recursive) contents of the user's inventory. If the room is dark, objects in the room should not be included in this list.

**Comment by 1Bayshore** [comment]
I think we already fixed this in the `plurals_and_money` branch, so we can close this when we remerge that branch.

**Comment by 1Bayshore** [comment]
This has been partially solved, see #102 for more discussion about this.
