### ISSUE TITLE
Enhanced logging and filtering/monitoring support

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#75]
Currently logging is something of a mess. Every single debug comment from every time the game is run gets appended to a single text log file, which is therefore vast and difficult to work with. Meanwhile wizards have limited ability to control which debug comments they see: the `verbose` command takes a single verbosity level, which if set to high creates an untenable amount of debug chatter, or takes a list of "filter" words that cause printing of any debug message matching one of those words (in the message itself or in the classes and functions of its call stack). And debug messages are not emitted to the wizard who requested them, but simply sent to the game server's stdout using `print()`. 

Python has reasonably powerful standard logging tools (`import logger` I believe) and there are third-party libraries which allow very flexible monitoring, compression and eventual deletion or archiving of old logs, etc. I think the right solution is to use a better logging tool for all the debug messages, then allow individual wizards to register filter criteria (combinations of things like verbosity level, search strings, maybe regular expressions or even SQL queries). Then any log messages matching a given wizard's filtering criteria will be automatically printed out on their console, perhaps optionally redirected into a separate file.

**Comment by 1Bayshore** [comment]
I did some work on this while implementing #83. We now allow wizards to specify their filter criteria, and the messages are directed into their console. However, the log file is still enormous, named `test_log.txt`, and not always saved properly. I like the idea about allowing wizards to generate their own files for their own use, but that's not exactly a high priority.

**Comment by 1Bayshore** [comment]
I believe that we fixed this with #136. Closing now.
