### ISSUE TITLE
Implementing Magic

### ISSUE THREAD

**Issue by 1Bayshore** [davedotluebke/old-skool-text-game#85]
We've been hoping to implement a system of magic in the game. Here's our current plan:
- [x] Every player has an intrinsic `mana`, or magic power. 
- [x] Players can use their `mana` to cast spells.
- [x] Wizards will be able to create spells that players can cast.
  - [x] Players will `learn` spells from books and scrolls. When the players learn the spell, it will be appended to a dictionary. The spell will also be added as an `Action`.
  ~_IMPORTANT NOTE: This change means that players will have to store their own_ `actions` _dictionary, as they will now be different from each other._
    We also need to remember to add the spells as actions again during the loading process.~
  - [x] We will create a `spells.py` file with various helper functions for spells.
- [x] Players generate `mana` slowly over time.
- [x] The maximum amount of `mana` a player can store is set in their `max_mana` attribute.
   - [ ] Players' `max_mana` will grow as they complete quests and become more powerful.
- [x] `mana` can also be stored in emeralds.
  - [x] Emeralds also have a `max_mana` capacity.
  - [x] Players can put `mana` in emeralds and bring it back into themselves with minimal loss.
  - [x] Players can also cast spells directly from emeralds. This allows them to cast spells above their `max_mana`, however, this also significantly shrinks the emeralds `max_mana` (possibly by the amount of `mana` used for the spell).
- [x] Players also have a `magic_skill`. This represents the maximum amount of `mana` they can safely handle at once.
  - [ ] Like the `max_mana` attribute, a player's `magic_skill` will grow as they complete quests and become more experienced.
  - [x] If players cast a spell above their `magic_skill`, they are drawing on forces beyond their level of control. They can do this, but at great risk. Players casting a spell above their `max_mana` risk taking damage. 

**Possible adjustment: Making** `max_mana` **and** `magic_skill` **the same attribute**
Since the `magic_skill` and the `max_mana` attributes are related (`magic_skill` is always greater than `max_mana`, and they both grow as players become more experienced), we were thinking about possibly making them one attribute (and calculating the other on demand). For example, `magic_skill` could always be twice as much as `max_mana`. We will consider this option as we implement this.

**Grinding for emeralds**
With the proposed system, players will always want more emeralds. We could potentially use the `room_factory` branch's endless caverns to allow for this.

**Comment by rivques** [comment]
Things that need to be implemented:

- [ ] Emeralds
- [ ] The `learn` command
- [ ] Add the attributes to the player
- [ ] Make players store their own `actions` dictionary

**Comment by 1Bayshore** [comment]
This is now almost complete. Moving `max_mana` increases to #164 and conventions files to #150 and closing this.
