### ISSUE TITLE
Python Path: Should we add this to GitIgnore?

### ISSUE THREAD

**Issue by 1Bayshore** [davedotluebke/old-skool-text-game#88]
For a long time now, we have been using Visual Studio Code to debug the program. However, there is an annoying problem that keep occurring: Whenever somebody commits the `settings.json` file that stores the VSCode state, it commits the python path (which is different on windows and mac), and the next person to clone or pull the game has to re-select the python version they want. This then becomes a tracked file, and they have to commit it before checking out to another branch, changing the python path stored on GitHub. We should find a way to avoid this problem, even if it's as simple as adding the `vscode` directory to the `.gitignore` file.

**Comment by rivques** [comment]
Fixed, for real this time. At least on my computer. You might need to run `git rm .vscode/settings.json -f`.
