### ISSUE TITLE
NPC behaviors

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#9]
Support NPCs that:
- [x] Move around by picking exits at random
- [x] Respect safe-zone attribute on rooms 
- [x] Say various things (support both random comments and reading from a script)
- [x] Fight creatures they encounter, if they are aggressive

**Comment by 1Bayshore** [comment]
I added the ability to read from a script.

**Comment by davedotluebke** [comment]
Checked it off the list.
