### ISSUE TITLE
Console doesn't print blank lines or certain null commands

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#96]
Currently when you just type <return> at the command prompt, entering a blank string as your command, the parser returns True and a blank `> ` prompt is printed - but that doesn't actually show up in the console until a valid command is entered. Try hitting <return> several times and then typing "look" or some other valid command. 

Today I noticed other commands behaving the same way. "verbose" and "execute" were both swallowed because I didn't have wizard privileges, and didn't even echo to the console until I entered some other, valid command later. 

Not sure if this is a problem in the console or the webclient. Guessing console.

**Comment by 1Bayshore** [comment]
@davedotluebke we already fixed this in the `master` branch, but for some reason the bug still exists in the `plurals_and_money` branch.
